package Sintatico;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public class FirstFollowSets {
    // First Sets
    public static final Set<String> FIRST_LEIA = new HashSet<>(Arrays.asList("LEIA"));
    public static final Set<String> FIRST_PONTO_E_VIRGULA = new HashSet<>(Arrays.asList("PONTO_E_VIRGULA"));
    public static final Set<String> FIRST_PROGRAMA = new HashSet<>(Arrays.asList("FUNCAO"));
    public static final Set<String> FIRST_BLOCO = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FIRST_COMANDO = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE"));
    public static final Set<String> FIRST_DECLARACAO = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO"));
    public static final Set<String> FIRST_ATRIBUICAO = new HashSet<>(Arrays.asList("IDENTIFICADOR"));
    public static final Set<String> FIRST_INCREMENTO = new HashSet<>(Arrays.asList("INCREMENTO", "DECREMENTO"));
    public static final Set<String> FIRST_TIPO = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO"));
    public static final Set<String> FIRST_ID = new HashSet<>(Arrays.asList("IDENTIFICADOR"));
    public static final Set<String> FIRST_NUM = new HashSet<>(Arrays.asList("INTEIRO", "DECI"));
    public static final Set<String> FIRST_BOOLEAN = new HashSet<>(Arrays.asList("BOOLEAN"));
    public static final Set<String> FIRST_VALOR = new HashSet<>(Arrays.asList("IDENTIFICADOR", "INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO"));
    public static final Set<String> FIRST_EXPRESSAO = new HashSet<>(Arrays.asList("IDENTIFICADOR", "INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "ABRE_PARENTESES", "INT", "FLOAT", "BOOLEANO", "TEXTO"));
    public static final Set<String> FIRST_OPERACAO_MATEMATICA = new HashSet<>(Arrays.asList("IDENTIFICADOR", "INTEIRO", "DECI", "ABRE_PARENTESES"));
    public static final Set<String> FIRST_EXPR_MAT = new HashSet<>(Arrays.asList("SOMA", "SUBTRACAO", "EOF"));
    public static final Set<String> FIRST_TERMO = new HashSet<>(Arrays.asList("IDENTIFICADOR", "INTEIRO", "DECIMAL", "ABRE_PARENTESES"));
    public static final Set<String> FIRST_TERMO_LINHA = new HashSet<>(Arrays.asList("MULTIPLICACAO", "DIVISAO", "EOF"));
    public static final Set<String> FIRST_FATOR = new HashSet<>(Arrays.asList("IDENTIFICADOR", "INTEIRO", "DECI", "ABRE_PARENTESES"));
    public static final Set<String> FIRST_EXPRESSAO_LOGICA = new HashSet<>(Arrays.asList("IDENTIFICADOR", "INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "ABRE_PARENTESES", "INT", "FLOAT", "BOOLEANO", "TEXTO"));
    public static final Set<String> FIRST_EXPRESSAO_LOGICA_L = new HashSet<>(Arrays.asList("SOMA", "SUBTRACAO", "MULTIPLICACAO", "DIVISAO", "MENOR", "MAIOR", "MENOR_IGUAL", "MAIOR_IGUAL", "IGUAL", "DIFERENTE", "E_LOGICO", "OU_LOGICO", "EOF"));
    public static final Set<String> FIRST_OPERADOR_ARITIMETICO = new HashSet<>(Arrays.asList("SOMA", "SUBTRACAO", "MULTIPLICACAO", "DIVISAO"));
    public static final Set<String> FIRST_OPERADOR_RELACIONAL = new HashSet<>(Arrays.asList("MENOR", "MAIOR", "MENOR_IGUAL", "MAIOR_IGUAL", "IGUAL", "DIFERENTE"));
    public static final Set<String> FIRST_OPERADOR_LOGICO = new HashSet<>(Arrays.asList("E_LOGICO", "OU_LOGICO"));
    public static final Set<String> FIRST_SE = new HashSet<>(Arrays.asList("SE"));
    public static final Set<String> FIRST_SE_AUX = new HashSet<>(Arrays.asList("SENAO_SE", "SENAO", "EOF"));
    public static final Set<String> FIRST_REPETICAO = new HashSet<>(Arrays.asList("ENQUANTO", "PARA"));
    public static final Set<String> FIRST_ENQUANTO = new HashSet<>(Arrays.asList("ENQUANTO"));
    public static final Set<String> FIRST_FUNCAO = new HashSet<>(Arrays.asList("FUNCAO"));
    public static final Set<String> FIRST_PARAMETROS = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "EOF"));
    public static final Set<String> FIRST_PARAMETRO = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "EOF"));
    public static final Set<String> FIRST_CHAMADA_FUNCAO = new HashSet<>(Arrays.asList("IDENTIFICADOR"));
    public static final Set<String> FIRST_ARGUMENTOS = new HashSet<>(Arrays.asList("IDENTIFICADOR", "INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO"));
    public static final Set<String> FIRST_ARGUMENTO = new HashSet<>(Arrays.asList("VIRGULA", "EOF"));
    public static final Set<String> FIRST_RETORNO = new HashSet<>(Arrays.asList("RETORNO"));
    public static final Set<String> FIRST_ESCREVA = new HashSet<>(Arrays.asList("ESCREVA"));
    public static final Set<String> FIRST_EXECUTE = new HashSet<>(Arrays.asList("EXECUTE"));
    public static final Set<String> FIRST_OP_ATRIB = new HashSet<>(Arrays.asList("RECEBE", "RECEBE_INC", "RECEBE_DEC", "INCREMENTO", "DECREMENTO"));

    // Follow Sets
    public static final Set<String> FOLLOW_PROGRAMA = new HashSet<>(Arrays.asList("EOF"));
    public static final Set<String> FOLLOW_BLOCO = new HashSet<>(Arrays.asList("EOF"));
    public static final Set<String> FOLLOW_COMANDO = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_DECLARACAO = new HashSet<>(Arrays.asList("FECHA_CHAVE", "INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_ATRIBUICAO = new HashSet<>(Arrays.asList("FECHA_CHAVE","INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_INCREMENTO = new HashSet<>(Arrays.asList("FECHA_CHAVE", "INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_TIPO = new HashSet<>(Arrays.asList("IDENTIFICADOR"));
    public static final Set<String> FOLLOW_ID = new HashSet<>(Arrays.asList("ATRIBUICAO", "SOMA_ATRIBUICAO", "SUBTRACAO_ATRIBUICAO", "INCREMENTO", "DECREMENTO", "PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA"));
    public static final Set<String> FOLLOW_NUM = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA", "SOMA", "SUBTRACAO", "MULTIPLICACAO", "DIVISAO", "MENOR", "MAIOR", "MENOR_IGUAL", "MAIOR_IGUAL", "IGUAL", "DIFERENTE"));
    public static final Set<String> FOLLOW_BOOLEAN = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA", "MENOR", "MAIOR", "MENOR_IGUAL", "MAIOR_IGUAL", "IGUAL", "DIFERENTE"));
    public static final Set<String> FOLLOW_VALOR = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA", "SOMA", "SUBTRACAO", "MULTIPLICACAO", "DIVISAO", "MENOR", "MAIOR", "MENOR_IGUAL", "MAIOR_IGUAL", "IGUAL", "DIFERENTE"));
    public static final Set<String> FOLLOW_EXPRESSAO = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA"));
    public static final Set<String> FOLLOW_OPERACAO_MATEMATICA = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA", "MENOR", "MAIOR", "MENOR_IGUAL", "MAIOR_IGUAL", "IGUAL", "DIFERENTE"));
    public static final Set<String> FOLLOW_EXPR_MAT = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA", "MENOR", "MAIOR", "MENOR_IGUAL", "MAIOR_IGUAL", "IGUAL", "DIFERENTE"));
    public static final Set<String> FOLLOW_TERMO = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA", "SOMA", "SUBTRACAO", "MENOR", "MAIOR", "MENOR_IGUAL", "MAIOR_IGUAL", "IGUAL", "DIFERENTE"));
    public static final Set<String> FOLLOW_TERMO_LINHA = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA", "SOMA", "SUBTRACAO", "MENOR", "MAIOR", "MENOR_IGUAL", "MAIOR_IGUAL", "IGUAL", "DIFERENTE"));
    public static final Set<String> FOLLOW_FATOR = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA", "SOMA", "SUBTRACAO", "MULTIPLICACAO", "DIVISAO", "MENOR", "MAIOR", "MENOR_IGUAL", "MAIOR_IGUAL", "IGUAL", "DIFERENTE"));
    public static final Set<String> FOLLOW_EXPRESSAO_LOGICA = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA"));
    public static final Set<String> FOLLOW_EXPRESSAO_LOGICA_L = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA"));
    public static final Set<String> FOLLOW_OPERADOR_ARITIMETICO = new HashSet<>(Arrays.asList("IDENTIFICADOR", "INTEIRO", "DECI", "ABRE_PARENTESES"));
    public static final Set<String> FOLLOW_OPERADOR_RELACIONAL = new HashSet<>(Arrays.asList("IDENTIFICADOR", "INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "ABRE_PARENTESES"));
    public static final Set<String> FOLLOW_OPERADOR_LOGICO = new HashSet<>(Arrays.asList("IDENTIFICADOR", "INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "ABRE_PARENTESES"));
    public static final Set<String> FOLLOW_SE = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_SE_AUX = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_REPETICAO = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_ENQUANTO = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_FUNCAO = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_PARAMETROS = new HashSet<>(Arrays.asList("FECHA_PARENTESES"));
    public static final Set<String> FOLLOW_PARAMETRO = new HashSet<>(Arrays.asList("VIRGULA", "FECHA_PARENTESES"));
    public static final Set<String> FOLLOW_CHAMADA_FUNCAO = new HashSet<>(Arrays.asList("PONTO_VIRGULA", "FECHA_PARENTESES", "VIRGULA"));
    public static final Set<String> FOLLOW_ARGUMENTOS = new HashSet<>(Arrays.asList("FECHA_PARENTESES"));
    public static final Set<String> FOLLOW_ARGUMENTO = new HashSet<>(Arrays.asList("FECHA_PARENTESES"));
    public static final Set<String> FOLLOW_RETORNO = new HashSet<>(Arrays.asList("FECHA_CHAVES"));
    public static final Set<String> FOLLOW_ESCREVA = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_EXECUTE = new HashSet<>(Arrays.asList("INTEIRO", "DECIMAL", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
    public static final Set<String> FOLLOW_OP_ATRIB = new HashSet<>(Arrays.asList("INT", "FLOAT", "BOOLEANO", "TEXTO", "IDENTIFICADOR", "SE", "ENQUANTO", "PARA", "FUNCAO", "ESCREVA", "EXECUTE", "EOF"));
} 